FROM ubuntu:14.04

WORKDIR /app
COPY . .

# Atualiza as dependências
RUN apt-get update && apt-get upgrade -y


# Instala Python 2.7
RUN apt-get install -y python2.7 
RUN apt-get install -y python-pip
RUN apt-get install -y python-setuptools 
RUN apt-get install -y curl
RUN apt-get install -y build-essential
RUN apt-get install -y python-virtualenv


RUN chmod +x entrypoint.sh

ENTRYPOINT ["/app/entrypoint.sh"]