version: '3.7'
services:

  # Serviço de Banco de Dados
  database:
    image: postgis/postgis:15-3.4
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - cmb-network
    ports:
      - 5499:5432
    volumes:
      - ./data/db-data:/var/lib/postgresql/data
    restart: always


  # Serviço de Nominatim, que faz a geocodificação
  nominatim:
    container_name: nominatim
    image: mediagis/nominatim:4.2
    restart: always
    ports:
      - "8088:8080"
    networks:
      - cmb-network
    environment:
      # see https://github.com/mediagis/nominatim-docker/tree/master/4.2#configuration for more options
      PBF_URL: https://download.geofabrik.de/south-america/brazil/sudeste-latest.osm.pbf
      REPLICATION_URL: https://download.geofabrik.de/south-america/brazil/sudeste-updates/
      NOMINATIM_PASSWORD: password
    volumes:
      - ./data/nominatim-data:/var/lib/postgresql/14/main
    shm_size: 1gb
    depends_on:
      - database

  
  # Aplicação principal, que executa a API e faz o ETL
  backend:
    build: 
      context: ./src/backend
      dockerfile: Dockerfile
    networks:
      - cmb-network
    dns: 
      - 8.8.8.8
      - 8.8.4.4
    ports:
      - 5678:5678
    depends_on:
      - database
      - nominatim
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_SCHEMA=${POSTGRES_SCHEMA}
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
    volumes:
      - ./src/backend:/app
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always

  
  # Frontend da aplicação em Vue.js
  frontend:
    build:
      context: ./src
      dockerfile: Dockerfile-front
    ports:
      - 8080:8080
      - 5000:5000 #To flaks API
      - 53350:53350 #To web-debug
    volumes:
      - ./src/frontend:/app
    networks:
      - cmb-network
    depends_on:
      - database
      - nominatim 
    restart: always
    

networks:
  cmb-network: